name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    # deploy only if the ci pipeline was successful 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish .NET Core Project
      run: dotnet publish src/Piet.Web/Piet.Web.csproj -c Release -o release --nologo
    
    - name: Change base-tag in index.html from / to piet
      run: sed -i 's/<base href="\/" \/>/<base href="\/piet\/" \/>/g' release/wwwroot/index.html
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: release/wwwroot

